// this file is auto-generated by running myFile.py file
export const links = [
  { id: "00", name: "setup", path: "/lessons/00-setup" },
  {
    id: "01",
    name: "foundations of web development",
    path: "/lessons/01-foundations-of-web-development",
  },
  { id: "02", name: "react basics", path: "/lessons/02-react-basics" },
  {
    id: "03",
    name: "react intermediate",
    path: "/lessons/03-react-intermediate",
  },
  { id: "04", name: "react advanced", path: "/lessons/04-react-advanced" },
  { id: "05", name: "react router", path: "/lessons/05-react-router" },
  { id: "06", name: "react query", path: "/lessons/06-react-query" },
  { id: "07", name: "react testing", path: "/lessons/07-react-testing" },
  { id: "08", name: "react toolkit", path: "/lessons/08-react-toolkit" },
  { id: "09", name: "practical react", path: "/lessons/09-practical-react" },
  { id: "10", name: "nextJS", path: "/lessons/10-nextjs" },
];

export const completion_status = {
  "00-setup": false,
  "01-foundations-of-web-development": false,
  "02-react-basics": false,
  "03-react-intermediate": false,
  "04-react-advanced": false,
  "05-react-router": false,
  "06-react-query": false,
  "07-react-testing": false,
  "08-react-toolkit": false,
  "09-practical-react": false,
  "10-nextjs": false,
};
